# AUTO-GENERATED by scripts/gen.py from the live JSON Schemas. Do not edit by hand.
# Built by Blockchain Lab — https://blockchainlab.com
from __future__ import annotations
from typing import Any, Dict, List, Optional, TypedDict, Union


BipsRow = TypedDict('BipsRow', {'number': Optional[float], 'title': Optional[str], 'status': Optional[str], 'type': Optional[str], 'layer': Optional[str], 'url': Optional[str]}, total=False)

BipsRows = List["BipsRow"]


class BridgesRow(TypedDict, total=False):
    rank: Optional[float]
    name: Optional[str]
    slug: Optional[str]
    category: Optional[str]
    chains: List[Optional[str]]
    tvl_usd: Optional[float]
    change_7d_pct: Optional[float]
    url: Optional[str]
    audits: Optional[str]
    defillama_url: Optional[str]

BridgesRows = List["BridgesRow"]


class ChainsRowNativecurrency(TypedDict, total=False):
    name: Optional[str]
    symbol: Optional[str]
    decimals: Optional[float]

class ChainsRowExplorersItem(TypedDict, total=False):
    name: Optional[str]
    url: Optional[str]
    standard: Optional[str]

class ChainsRow(TypedDict, total=False):
    chainId: Optional[float]
    name: Optional[str]
    shortName: Optional[str]
    chain: Optional[str]
    nativeCurrency: "ChainsRowNativecurrency"
    rpc: List[Optional[str]]
    explorers: List["ChainsRowExplorersItem"]
    infoURL: Optional[str]
    testnet: Optional[bool]
    status: Optional[str]

ChainsRows = List["ChainsRow"]


class ChainsTvlRow(TypedDict, total=False):
    rank: Optional[float]
    name: Optional[str]
    chainId: Optional[Union[float, str]]
    token: Optional[str]
    tvl_usd: Optional[float]
    defillama_url: Optional[str]

ChainsTvlRows = List["ChainsTvlRow"]


class DexVolumesRow(TypedDict, total=False):
    rank: Optional[float]
    name: Optional[str]
    slug: Optional[str]
    category: Optional[str]
    chains: List[Optional[str]]
    total_24h_usd: Optional[float]
    total_7d_usd: Optional[float]
    total_30d_usd: Optional[float]
    change_1d_pct: Optional[float]
    change_7d_pct: Optional[float]
    defillama_url: Optional[str]

DexVolumesRows = List["DexVolumesRow"]


EipsRow = TypedDict('EipsRow', {'number': Optional[float], 'title': Optional[str], 'status': Optional[str], 'type': Optional[str], 'category': Optional[str], 'created': Optional[str], 'requires': List[Optional[float]], 'url': Optional[str]}, total=False)

EipsRows = List["EipsRow"]


ErcsRow = TypedDict('ErcsRow', {'number': Optional[float], 'title': Optional[str], 'status': Optional[str], 'type': Optional[str], 'category': Optional[str], 'created': Optional[str], 'requires': List[Optional[float]], 'url': Optional[str]}, total=False)

ErcsRows = List["ErcsRow"]


EventsRow = TypedDict('EventsRow', {'source': Optional[str], 'id': Optional[str], 'title': Optional[str], 'url': Optional[str], 'organizer': Optional[str], 'type': Optional[str], 'start': Optional[str], 'end': Optional[str], 'medium': Optional[str], 'verified': Optional[str], 'dates': Optional[str]}, total=False)

EventsRows = List["EventsRow"]


class FeesRow(TypedDict, total=False):
    rank: Optional[float]
    name: Optional[str]
    slug: Optional[str]
    category: Optional[str]
    chains: List[Optional[str]]
    total_24h_usd: Optional[float]
    total_7d_usd: Optional[float]
    total_30d_usd: Optional[float]
    change_1d_pct: Optional[float]
    change_7d_pct: Optional[float]
    defillama_url: Optional[str]

FeesRows = List["FeesRow"]


class GlossaryRow(TypedDict, total=False):
    kind: Optional[str]
    slug: Optional[str]
    term: Optional[str]
    definition: Optional[str]
    detail: Optional[str]
    url: Optional[str]

GlossaryRows = List["GlossaryRow"]


GrantsRow = TypedDict('GrantsRow', {'id': Optional[str], 'name': Optional[str], 'ecosystem': Optional[str], 'operator': Optional[str], 'url': Optional[str], 'type': Optional[str], 'link_status': Optional[float], 'link_checked_at': Optional[str]}, total=False)

GrantsRows = List["GrantsRow"]


class HackathonsRow(TypedDict, total=False):
    source: Optional[str]
    id: Optional[str]
    title: Optional[str]
    url: Optional[str]
    organizer: Optional[str]
    dates: Optional[str]
    state: Optional[str]
    prize: Optional[str]
    location: Optional[str]
    registrations: Optional[float]
    themes: List[Optional[str]]
    verified: Optional[str]
    first_seen: Optional[str]
    new: Optional[bool]

HackathonsRows = List["HackathonsRow"]


class L2MetricsRowTvsBreakdown(TypedDict, total=False):
    native: Optional[float]
    canonical: Optional[float]
    external: Optional[float]
    ether: Optional[float]
    stablecoin: Optional[float]
    btc: Optional[float]

class L2MetricsRowRisksItem(TypedDict, total=False):
    name: Optional[str]
    value: Optional[str]
    sentiment: Optional[str]

L2MetricsRow = TypedDict('L2MetricsRow', {'id': Optional[str], 'name': Optional[str], 'type': Optional[str], 'host_chain': Optional[str], 'category': Optional[str], 'stack': List[Optional[str]], 'purposes': List[Optional[str]], 'stage': Optional[str], 'under_review': Optional[bool], 'tvs_usd': Optional[float], 'tvs_breakdown': "L2MetricsRowTvsBreakdown", 'tvs_change_7d_pct': Optional[float], 'risks': List["L2MetricsRowRisksItem"], 'l2beat_url': Optional[str]}, total=False)

L2MetricsRows = List["L2MetricsRow"]


class ProtocolsRow(TypedDict, total=False):
    rank: Optional[float]
    name: Optional[str]
    slug: Optional[str]
    category: Optional[str]
    chains: List[Optional[str]]
    tvl_usd: Optional[float]
    change_1d_pct: Optional[float]
    change_7d_pct: Optional[float]
    url: Optional[str]
    defillama_url: Optional[str]

ProtocolsRows = List["ProtocolsRow"]


class RpcHealthRow(TypedDict, total=False):
    chain: Optional[str]
    chain_id: Optional[float]
    url: Optional[str]
    ok: Optional[bool]
    latency_ms: Optional[float]
    block: Optional[float]
    chain_id_ok: Optional[bool]
    lag_blocks: Optional[float]
    healthy: Optional[bool]
    checked_at: Optional[str]
    error: Optional[str]

RpcHealthRows = List["RpcHealthRow"]


class SanctionedAddressesRow(TypedDict, total=False):
    chain: Optional[str]
    address: Optional[str]

SanctionedAddressesRows = List["SanctionedAddressesRow"]


class SecurityIncidentsRow(TypedDict, total=False):
    date: Optional[str]
    name: Optional[str]
    classification: Optional[str]
    technique: Optional[str]
    amount_usd: Optional[float]
    returned_usd: Optional[float]
    chains: List[Optional[str]]
    bridge_hack: Optional[bool]
    target_type: Optional[str]
    source: Optional[Any]
    defillama_id: Optional[str]

SecurityIncidentsRows = List["SecurityIncidentsRow"]


class StablecoinsRow(TypedDict, total=False):
    id: Optional[str]
    name: Optional[str]
    symbol: Optional[str]
    peg_type: Optional[str]
    peg_mechanism: Optional[str]
    price: Optional[float]
    circulating: Optional[float]
    change_1d_pct: Optional[float]
    change_7d_pct: Optional[float]
    change_30d_pct: Optional[float]
    chains: List[Optional[str]]
    defillama_url: Optional[str]

StablecoinsRows = List["StablecoinsRow"]


class WhitepapersRow(TypedDict, total=False):
    id: Optional[str]
    slug: Optional[str]
    title: Optional[str]
    authors: Optional[str]
    year: Optional[float]
    category: Optional[str]
    paper_type: Optional[str]
    topics: List[Optional[str]]
    original_source_url: Optional[str]
    blockchainlab_url: Optional[str]

WhitepapersRows = List["WhitepapersRow"]


class YieldsRow(TypedDict, total=False):
    pool: Optional[str]
    project: Optional[str]
    chain: Optional[str]
    symbol: Optional[str]
    tvl_usd: Optional[float]
    apy: Optional[float]
    apy_base: Optional[float]
    apy_reward: Optional[float]
    apy_mean_30d: Optional[float]
    stablecoin: Optional[bool]
    il_risk: Optional[str]
    exposure: Optional[str]
    defillama_url: Optional[str]

YieldsRows = List["YieldsRow"]

