# Generate typed SDK models from the live Blockchain Lab Open Data API JSON Schemas.
# usage: python3 scripts/gen.py [api_base]  -> ts/src/types.ts, python/blockchainlab_sdk/types.py, ts/src/datasets.ts
import json, sys, urllib.request, re
BASE = (sys.argv[1] if len(sys.argv) > 1 else "https://blockchains.github.io/blockchainlab-api").rstrip("/")
def get(u): return json.load(urllib.request.urlopen(urllib.request.Request(u, headers={"user-agent": "blockchainlab-sdk-gen"}), timeout=60))
idx = get(f"{BASE}/v1/index.json")
def pascal(s): return "".join(p.capitalize() for p in re.split(r"[^a-zA-Z0-9]", s) if p)
def camel(s): p = pascal(s); return p[0].lower() + p[1:]
def snake(s): return re.sub(r"[^a-zA-Z0-9]", "_", s)
ts, py = [], []
ts.append("// AUTO-GENERATED by scripts/gen.py from the live JSON Schemas. Do not edit by hand.\n// Built by Blockchain Lab — https://blockchainlab.com\n")
py.append("# AUTO-GENERATED by scripts/gen.py from the live JSON Schemas. Do not edit by hand.\n# Built by Blockchain Lab — https://blockchainlab.com\nfrom __future__ import annotations\nfrom typing import Any, Dict, List, Optional, TypedDict, Union\n")
def ts_type(s, name, out):
    t = s.get("type", "object"); types = t if isinstance(t, list) else [t]
    parts = []
    for ty in types:
        if ty == "null": parts.append("null")
        elif ty in ("number", "integer"): parts.append("number")
        elif ty == "string": parts.append("string")
        elif ty == "boolean": parts.append("boolean")
        elif ty == "array": parts.append(f"Array<{ts_type(s.get('items', {}), name + 'Item', out) if s.get('items') else 'unknown'}>")
        elif ty == "object":
            if s.get("properties"):
                out.append(ts_iface(s, name, out)); parts.append(name)
            else: parts.append("Record<string, unknown>")
    return " | ".join(dict.fromkeys(parts)) or "unknown"
def ts_iface(s, name, out):
    req = set(s.get("required", [])); lines = [f"export interface {name} {{"]
    for k, v in s.get("properties", {}).items():
        key = k if re.match(r"^[A-Za-z_$][\w$]*$", k) else json.dumps(k)
        lines.append(f"  {key}{'' if k in req else '?'}: {ts_type(v, name + pascal(k), out)};")
    lines.append("}"); return "\n".join(lines)
PY_KW = {"from", "class", "def", "return", "type", "global", "in", "is", "not", "or", "and", "import", "pass", "lambda"}
def py_type(s, name, out):
    t = s.get("type", "object"); types = t if isinstance(t, list) else [t]; parts = []; nullable = "null" in types
    for ty in types:
        if ty == "null": continue
        elif ty in ("number", "integer"): parts.append("float")
        elif ty == "string": parts.append("str")
        elif ty == "boolean": parts.append("bool")
        elif ty == "array": parts.append(f"List[{py_type(s.get('items', {}), name + 'Item', out) if s.get('items') else 'Any'}]")
        elif ty == "object":
            if s.get("properties"): out.append(py_td(s, name, out)); parts.append(f'"{name}"')
            else: parts.append("Dict[str, Any]")
    parts = list(dict.fromkeys(parts)) or ["Any"]
    t = parts[0] if len(parts) == 1 else f"Union[{', '.join(parts)}]"
    return f"Optional[{t}]" if nullable else t
def py_td(s, name, out):
    props = s.get("properties", {}); req = set(s.get("required", []))
    fields = {k: py_type(v, name + pascal(k), out) for k, v in props.items()}
    if any(not re.match(r"^[A-Za-z_]\w*$", k) or k in PY_KW for k in props):  # functional syntax for odd keys
        return f"{name} = TypedDict({name!r}, {{{', '.join(f'{k!r}: {v}' for k, v in fields.items())}}}, total=False)"
    body = "\n".join(f"    {k}: {v}" for k, v in fields.items()) or "    pass"
    return f"class {name}(TypedDict, total=False):\n{body}"
ds_ts, ds_py = [], []
for d in idx["datasets"]:
    n = d["dataset"]; sch = get(d["schema"]); P = pascal(n)
    item = sch["properties"]["data"]["items"]; out_ts, out_py = [], []
    row_ts = ts_type(item, P + "Row", out_ts); row_py = py_type(item, P + "Row", out_py)
    ts.extend(out_ts); ts.append(f"export type {P}Dataset = Envelope<{row_ts}>;\n")
    py.extend(out_py); py.append(f"{P}Rows = List[{row_py}]\n")
    ds_ts.append((n, P, d["description"])); ds_py.append((n, P, d["description"]))
ts.insert(1, """export interface Envelope<T> {
  dataset: string; api_version?: string; schema_version?: string; schema_url?: string; description?: string;
  generated_at: string; source: string; source_url: string; built_by?: string; licence_note?: string; count?: number;
  data: T[]; [extra: string]: unknown;
}
""")
open("ts/src/types.ts", "w").write("\n".join(ts))
open("python/blockchainlab_sdk/types.py", "w").write("\n\n".join(py) + "\n")
m = ["// AUTO-GENERATED dataset registry.", "import type * as T from './types.js';", "export const DATASETS = " + json.dumps({n: desc for n, _, desc in ds_ts}, indent=1) + " as const;", "export type DatasetName = keyof typeof DATASETS;", "export interface DatasetMap {"]
m += [f"  {json.dumps(n)}: T.{P}Dataset;" for n, P, _ in ds_ts] + ["}", f"export const SCHEMA_VERSION = {json.dumps(idx.get('schema_version'))};"]
open("ts/src/datasets.ts", "w").write("\n".join(m) + "\n")
open("python/blockchainlab_sdk/datasets.py", "w").write("# AUTO-GENERATED dataset registry.\nDATASETS = " + json.dumps({n: desc for n, _, desc in ds_py}, indent=1) + f"\nSCHEMA_VERSION = {json.dumps(idx.get('schema_version'))}\n")
print(len(ds_ts), "datasets ->", sum(1 for l in ts if l.startswith("export interface")), "TS interfaces")
