// AUTO-GENERATED by scripts/gen.py from the live JSON Schemas. Do not edit by hand.
// Built by Blockchain Lab — https://blockchainlab.com

export interface Envelope<T> {
  dataset: string; api_version?: string; schema_version?: string; schema_url?: string; description?: string;
  generated_at: string; source: string; source_url: string; built_by?: string; licence_note?: string; count?: number;
  data: T[]; [extra: string]: unknown;
}

export interface BipsRow {
  number: null | number;
  title: null | string;
  status: null | string;
  type: null | string;
  layer: null | string;
  url: null | string;
}
export type BipsDataset = Envelope<BipsRow>;

export interface BridgesRow {
  rank: null | number;
  name: null | string;
  slug: null | string;
  category: null | string;
  chains: Array<null | string>;
  tvl_usd: null | number;
  change_7d_pct: null | number;
  url: null | string;
  audits: null | string;
  defillama_url: null | string;
}
export type BridgesDataset = Envelope<BridgesRow>;

export interface ChainsRowNativecurrency {
  name: null | string;
  symbol: null | string;
  decimals: null | number;
}
export interface ChainsRowExplorersItem {
  name: null | string;
  url: null | string;
  standard: null | string;
}
export interface ChainsRow {
  chainId: null | number;
  name: null | string;
  shortName: null | string;
  chain: null | string;
  nativeCurrency: ChainsRowNativecurrency;
  rpc: Array<null | string>;
  explorers: Array<ChainsRowExplorersItem>;
  infoURL: null | string;
  testnet: boolean | null;
  status: null | string;
}
export type ChainsDataset = Envelope<ChainsRow>;

export interface ChainsTvlRow {
  rank: null | number;
  name: null | string;
  chainId: null | number | string;
  token: null | string;
  tvl_usd: null | number;
  defillama_url: null | string;
}
export type ChainsTvlDataset = Envelope<ChainsTvlRow>;

export interface DexVolumesRow {
  rank: null | number;
  name: null | string;
  slug: null | string;
  category: null | string;
  chains: Array<null | string>;
  total_24h_usd: null | number;
  total_7d_usd: null | number;
  total_30d_usd: null | number;
  change_1d_pct: null | number;
  change_7d_pct: null | number;
  defillama_url: null | string;
}
export type DexVolumesDataset = Envelope<DexVolumesRow>;

export interface EipsRow {
  number: null | number;
  title: null | string;
  status: null | string;
  type: null | string;
  category: null | string;
  created: null | string;
  requires: Array<null | number>;
  url: null | string;
}
export type EipsDataset = Envelope<EipsRow>;

export interface ErcsRow {
  number: null | number;
  title: null | string;
  status: null | string;
  type: null | string;
  category: null | string;
  created: null | string;
  requires: Array<null | number>;
  url: null | string;
}
export type ErcsDataset = Envelope<ErcsRow>;

export interface EventsRow {
  source?: null | string;
  id?: null | string;
  title?: null | string;
  url?: null | string;
  organizer?: null | string;
  type?: null | string;
  start?: null | string;
  end?: null | string;
  medium?: null | string;
  verified?: null | string;
  dates?: null | string;
}
export type EventsDataset = Envelope<EventsRow>;

export interface FeesRow {
  rank: null | number;
  name: null | string;
  slug: null | string;
  category: null | string;
  chains: Array<null | string>;
  total_24h_usd: null | number;
  total_7d_usd: null | number;
  total_30d_usd: null | number;
  change_1d_pct: null | number;
  change_7d_pct: null | number;
  defillama_url: null | string;
}
export type FeesDataset = Envelope<FeesRow>;

export interface GlossaryRow {
  kind: null | string;
  slug: null | string;
  term: null | string;
  definition: null | string;
  detail: null | string;
  url: null | string;
}
export type GlossaryDataset = Envelope<GlossaryRow>;

export interface GrantsRow {
  id: null | string;
  name: null | string;
  ecosystem: null | string;
  operator: null | string;
  url: null | string;
  type: null | string;
  link_status: null | number;
  link_checked_at: null | string;
}
export type GrantsDataset = Envelope<GrantsRow>;

export interface HackathonsRow {
  source?: null | string;
  id?: null | string;
  title?: null | string;
  url?: null | string;
  organizer?: null | string;
  dates?: null | string;
  state?: null | string;
  prize?: null | string;
  location?: null | string;
  registrations?: null | number;
  themes?: Array<null | string>;
  verified?: null | string;
  first_seen?: null | string;
  new?: boolean | null;
}
export type HackathonsDataset = Envelope<HackathonsRow>;

export interface L2MetricsRowTvsBreakdown {
  native: null | number;
  canonical: null | number;
  external: null | number;
  ether: null | number;
  stablecoin: null | number;
  btc: null | number;
}
export interface L2MetricsRowRisksItem {
  name: null | string;
  value: null | string;
  sentiment: null | string;
}
export interface L2MetricsRow {
  id: null | string;
  name: null | string;
  type: null | string;
  host_chain: null | string;
  category: null | string;
  stack: Array<null | string>;
  purposes: Array<null | string>;
  stage: null | string;
  under_review: boolean | null;
  tvs_usd: null | number;
  tvs_breakdown: L2MetricsRowTvsBreakdown;
  tvs_change_7d_pct: null | number;
  risks: Array<L2MetricsRowRisksItem>;
  l2beat_url: null | string;
}
export type L2MetricsDataset = Envelope<L2MetricsRow>;

export interface ProtocolsRow {
  rank: null | number;
  name: null | string;
  slug: null | string;
  category: null | string;
  chains: Array<null | string>;
  tvl_usd: null | number;
  change_1d_pct: null | number;
  change_7d_pct: null | number;
  url: null | string;
  defillama_url: null | string;
}
export type ProtocolsDataset = Envelope<ProtocolsRow>;

export interface RpcHealthRow {
  chain: null | string;
  chain_id?: null | number;
  url: null | string;
  ok: boolean | null;
  latency_ms?: null | number;
  block?: null | number;
  chain_id_ok?: boolean | null;
  lag_blocks?: null | number;
  healthy: boolean | null;
  checked_at: null | string;
  error?: null | string;
}
export type RpcHealthDataset = Envelope<RpcHealthRow>;

export interface SanctionedAddressesRow {
  chain: null | string;
  address: null | string;
}
export type SanctionedAddressesDataset = Envelope<SanctionedAddressesRow>;

export interface SecurityIncidentsRow {
  date: null | string;
  name: null | string;
  classification: null | string;
  technique: null | string;
  amount_usd: null | number;
  returned_usd: null | number;
  chains: Array<null | string>;
  bridge_hack: boolean | null;
  target_type: null | string;
  source: null;
  defillama_id: null | string;
}
export type SecurityIncidentsDataset = Envelope<SecurityIncidentsRow>;

export interface StablecoinsRow {
  id: null | string;
  name: null | string;
  symbol: null | string;
  peg_type: null | string;
  peg_mechanism: null | string;
  price: null | number;
  circulating: null | number;
  change_1d_pct: null | number;
  change_7d_pct: null | number;
  change_30d_pct: null | number;
  chains: Array<null | string>;
  defillama_url: null | string;
}
export type StablecoinsDataset = Envelope<StablecoinsRow>;

export interface WhitepapersRow {
  id: null | string;
  slug: null | string;
  title: null | string;
  authors: null | string;
  year: null | number;
  category: null | string;
  paper_type: null | string;
  topics: Array<null | string>;
  original_source_url: null | string;
  blockchainlab_url: null | string;
}
export type WhitepapersDataset = Envelope<WhitepapersRow>;

export interface YieldsRow {
  pool: null | string;
  project: null | string;
  chain: null | string;
  symbol: null | string;
  tvl_usd: null | number;
  apy: null | number;
  apy_base: null | number;
  apy_reward: null | number;
  apy_mean_30d: null | number;
  stablecoin: boolean | null;
  il_risk: null | string;
  exposure: null | string;
  defillama_url: null | string;
}
export type YieldsDataset = Envelope<YieldsRow>;
